name: dsm_helper
description: 适用于群辉6.x的手机助手。采用新拟态设计风格

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.146+148

environment:
  sdk: '>=3.0.0 <4.0.0'

dependency_overrides:
  ffi: ^2.0.1  # open_file 3.2.1 需要重写
  http: ^1.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
#  dio: ^4.0.6
  dio: ^5.3.2
  #  fluttertoast: ^7.1.6
  fluttertoast: ^8.2.2
  package_info_plus: ^4.1.0
  sp_util: ^2.0.3
  permission_handler: ^11.0.1
  extended_image: ^8.1.1  # 8.0.0 起不再支持flutter3.7
  cool_ui: ^1.3.0
  gal: ^2.0.0
#  android_intent: ^2.0.2 方法已过时，无法编译通过
  android_intent_plus: ^4.0.3
  path_provider: ^2.1.1
  background_downloader: ^7.10.1
  percent_indicator: ^4.2.3
  fl_chart: ^0.63.0 # 0.63.0起不再支持flutter 3.7
  file_picker: ^5.5.0
  open_file: ^3.3.2
  flutter_datetime_picker_plus: ^2.1.0
#  flutter_datetime_picker:
#    git: https://github.com/Realank/flutter_datetime_picker.git
  flutter_swiper_null_safety: ^1.0.2
  html: ^0.15.4
  flutter_html: 3.0.0-beta.2
  provider: ^6.0.5
  wave: ^0.2.2
  modal_bottom_sheet: ^3.0.0-pre
  photo_manager: ^2.7.2
  flutter_vibrate: ^1.3.0
  url_launcher: ^6.1.14 # 6.1.12 起不再支持flutter3.7
  local_auth: ^2.1.7
  gesture_password_widget: ^2.0.1
  connectivity_plus: ^5.0.0
  code_editor: ^2.1.0
  flutter_highlight: ^0.7.0
#  syncfusion_flutter_charts: ^20.3.57
  syncfusion_flutter_charts: ^23.1.40
  syncfusion_flutter_pdfviewer: ^23.1.40
  syncfusion_flutter_datepicker: ^23.1.40
  syncfusion_flutter_gauges: ^23.1.40
  wechat_assets_picker: ^8.7.1  # 8.5.0 起不再支持flutter3.7
  fluwx: ^4.3.2
#  better_player:
#    git: https://github.com/AnonymHK/betterplayer.git
  device_info_plus: ^9.0.3
  xml2json: ^6.2.0 # 6.0.0起不支持 flutter 3.7
#  wake_on_lan: ^3.0.0
  dartssh2: ^2.8.2
  pangle_flutter: ^2.0.1  # 穿山甲广告 2.0.0起不支持 flutter 3.7
  xterm: ^3.5.0
  draggable_scrollbar: 0.1.0
  loading_animation_widget: ^1.2.0+4
#  draggable_scrollbar:
#    git: https://gitee.com/apaipai/draggable_scrollbar.git
#  receive_sharing_intent:
#    git: https://gitee.com/apaipai/receive_sharing_intent.git
  flutter_sharing_intent:
    git: https://gitee.com/apaipai/flutter_sharing_intent.git
  webview_flutter: ^4.2.4
  simple_logger: ^1.9.0+3
  extended_text: ^11.1.0  #11.0.0 起不支持flutter 3.7
  just_audio: ^0.9.35
  rxdart: ^0.27.7
  flutter_floating: ^1.0.8
  kumi_popup_window: ^2.0.1
  reorderables: ^0.6.0
#  fplayer: ^1.0.4
  fplayer:
    path: fplayer
  easy_app_installer: ^1.0.0
  quiver: ^3.2.1

  # drift 相关依赖
  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.17
  path: ^1.8.3

  # drift 依赖结束

  gbk_codec: ^0.4.0

  timelines: ^0.1.0
  flutter_slidable: ^3.0.0
#  flutter_filereader: ^3.0.0
#  x5_webview: ^0.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter

fluwx:
  app_id: 'wxabdf23571f34b49b'
  debug_logging: true # Logging in debug mode.
  android:
  #    interrupt_wx_request: true # Defaults to true.
  #    flutter_activity: 'MainActivity' # Defaults to app's launcher
  ios:
    universal_link: https://dsm.apaipai.top/app/
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tabbar/
    - assets/icons/
    - assets/icons/file_icons/
    - assets/devices/
    - assets/applications/
    - assets/applications/6/
    - assets/applications/7/
    - assets/control_panel/
    - assets/control_panel/6/
    - assets/control_panel/7/
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
